/* DO NOT EDIT THIS FILE - it is machine generated */


/* Header for class com_annotion_ruiyi_testsolog_JniHelper */


#ifdef __cplusplus
extern "C" {
#endif

char *hellolog();
char * secondLog();

#ifdef __cplusplus
}
#endif

